framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    # transports:
    #     # https://symfony.com/doc/current/messenger.html#transport-configuration
    #     async: '%env(MESSENGER_TRANSPORT_DSN)%'
    #     failed: 'doctrine://default?queue_name=failed'
    #     sync: 'sync://'
    transports:
      async:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          exchange:
            name: messages
            type: direct
          queues:
            messages: ~
      user_registered:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          exchange:
            name: user_events
            type: direct
          queues:
            user_registered_queue: ~

      user_email_sent:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          exchange:
            name: user_events
            type: direct
          queues:
            user_email_sent_queue:
              arguments:
                x-dead-letter-exchange: user_events
                x-dead-letter-routing-key: user_registered_queue

    routing:
      # Route your messages to the transports
      'App\Message\Domain\Message\Message': async
      # 'App\User\Domain\Event\UserRegisteredEvent': async
      'App\User\Domain\Event\UserRegisteredEvent': user_registered
      'App\User\Domain\Event\UserEmailSentEvent': user_email_sent
# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
