services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: sf7_php_ha
        volumes:
            - .:/var/www/rabbit-mq/
        networks:
            - symfony_network
        depends_on:
            - rabbitmq
            - redis
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: sf7_nginx_ha
        volumes:
            - .:/var/www/rabbit-mq/
        ports:
            - 80:80
        networks:
            - symfony_network
        depends_on:
            - php
    
    rabbitmq:
        image: rabbitmq:latest
        container_name: sf7_rabbitmq_ha
        restart: unless-stopped
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"  # Para acceder a la UI de RabbitMQ
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
            - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
        networks:
            - symfony_network

    redis:
        image: redis:latest
        container_name: sf7_redis_ha
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - symfony_network

    redis-commander:
        image: ghcr.io/joeferner/redis-commander:latest
        container_name: sf7_redis_commander
        restart: unless-stopped
        environment:
            - REDIS_HOSTS=local:dev.rabbit-mq.com
        ports:
            - "8081:8081"
        networks:
            - symfony_network
        depends_on:
            - redis

networks:
    symfony_network:

volumes:
  rabbitmq_data: